CREATE TABLE IF NOT EXISTS ServiceChain (
       id                    INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
       name                  VARCHAR(250) NOT NULL DEFAULT '' COMMENT 'CHAIN NAME',
       owner                 VARCHAR(250) NOT NULL DEFAULT '' COMMENT 'CHAIN OWNER INFO',
       is_use                SMALLINT(1) NOT NULL DEFAULT 0 COMMENT 'CHAIN IS USE FLAG',
       start_date            TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'CHAIN SERVICE START DATE',
       end_date              TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'CHAIN SERVICE END DATE',
       register              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CHAIN INFO REGISTER DATE',
       modify                TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'CHAIN INFO MODIFY DATE',
       ip_addr               VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'INFO UPDATE IP ADDR',
       PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS ServiceChainHost (
       id                    INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
       servicechain_id       INT(11) NOT NULL DEFAULT 0 COMMENT 'CHAIN INFO ID',
       host                  VARCHAR(150) NOT NULL DEFAULT '' COMMENT 'CHAIN HOST INFO',
       port                  SMALLINT(11) NOT NULL DEFAULT 0 COMMENT 'CHAIN HOST PORT INFO',
       is_use                SMALLINT(1) NOT NULL DEFAULT 0 COMMENT 'CHAIN HOST IS USE FLAG',
       category              VARCHAR(150) NOT NULL DEFAULT '' COMMENT 'CHAIN CATEGORY',
       rpc_type              SMALLINT(11) NOT NULL DEFAULT 1 COMMENT 'CHAIN RPC TYPE',
       is_alive              SMALLINT(1) NOT NULL DEFAULT 0 COMMENT 'CHAIN HOST IS ALIVE FLAG',
       register              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CHAIN HOST REGISTER DATE',
       modify                TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'CHAIN HOST MODIFY DATE',
       ip_addr               VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'HOST INFO UPDATE IP ADDR',
       PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE ServiceChainHostHealthCheck (
       id                    INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
       chain_host_id         INT(11) NOT NULL DEFAULT 0 COMMENT 'CHAIN HOST INFO ID',
       check_type            SMALLINT(11) NOT NULL DEFAULT 0 COMMENT 'HEALTH CHECK TYPE',
       comment               TEXT NOT NULL DEFAULT '' COMMENT 'CHAIN HOST HEALTH CHECK COMMENT',
       checkdate             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'HEALTH CHECK DATE',
       PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
