CREATE TABLE TxGatewayLog (
      id                                  INT(11) UNSIGNED AUTO_INCREMENT,
      method                              VARCHAR(100) DEFAULT '',
      query_string                        MEDIUMTEXT,
      request_uri                         VARCHAR(250) DEFAULT '',
      servlet_path                        VARCHAR(250) DEFAULT '',
      path_info                           VARCHAR(250) DEFAULT '',
      header_host                         VARCHAR(250) DEFAULT '',
      header_user_agent                   TINYTEXT,
      header_accept                       VARCHAR(150) DEFAULT '',
      header_accept_language              VARCHAR(250) DEFAULT '',
      header_accept_encoding              VARCHAR(250) DEFAULT '',
      header_referer                      VARCHAR(250) DEFAULT '',
      header_rpccaller                    VARCHAR(100) DEFAULT '',
      header_origin                       VARCHAR(250) DEFAULT '',
      header_connection                   VARCHAR(150) DEFAULT '',
      header_content_length               INT(11) DEFAULT 0,
      character_encoding                  VARCHAR(150) DEFAULT '',
      content_length                      INT(11) DEFAULT 0,
      content_type                        VARCHAR(150) DEFAULT '',
      local_addr                          VARCHAR(45) DEFAULT '127.0.0.1',
      locale                              VARCHAR(100) DEFAULT '',
      local_name                          VARCHAR(150) DEFAULT '',
      local_port                          VARCHAR(20) DEFAULT '80',
      protocol                            VARCHAR(150) DEFAULT '',
      remote_addr                         VARCHAR(45) DEFAULT '0.0.0.0',
      remote_host                         VARCHAR(150) DEFAULT '',
      remote_port                         VARCHAR(20) DEFAULT '0',
      scheme                              VARCHAR(100) DEFAULT 'http',
      server_name                         VARCHAR(250) DEFAULT '',
      server_port                         VARCHAR(20) DEFAULT '0',
      request_params                      TEXT,
      register                            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
